name: TEST
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "some"
        required: true
        type: choice
        options:
          - dev
          - test
          - stage
          - prod
      country:
        description: "some"
        required: true
        type: choice
        options:
          - arg
          - mex

env:
  ACCOUNT_ID:
    arg:
      dev: 146225626944
      test: 718892725114
      stage: 557653594106
      prod: 264394897793
    mex:
      dev: 223005233626
      stage: 741606091064
      prod: 829345317449
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: some
        run: |
          echo env.accountIds[inputs.country][inputs.environment]
          echo env.accountIds[${inputs.country}][${inputs.environment}]
