name: TEST
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "some"
        required: true
        type: choice
        options:
          - dev
          - test
          - stage
          - prod
      country:
        description: "some"
        required: true
        type: choice
        options:
          - arg
          - mex

env:
  arg_dev: "1"
  arg_prod: "2"
  mex_dev: "3"
  mex_prod: "4"
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: some
        run: |
          ref= '${{inputs.country}}_${{inputs.environment}}'
          echo env[${ref}]
