name: TEST
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "some"
        required: true
        type: choice
        options:
          - dev
          - test
          - stage
          - prod
      country:
        description: "some"
        required: true
        type: choice
        options:
          - arg
          - mex

env:
  ACCOUNT_ID: ${{ fromJson("{'arg':{'dev':'1','prod':'2'},'mex':{'dev':'3','prod':'4'}}") }}
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: some
        run: |
          echo env.accountIds[inputs.country][inputs.environment]
          echo env.accountIds[${inputs.country}][${inputs.environment}]
